### ISSUE TITLE
Members list update for SS2023

### ISSUE THREAD

**Issue by idilsulo** [womenincstum/womenincstum.github.io#10]
- [x] Archive WS2022 members
- [x] Add changes for new semester

**Comment by idilsulo** [comment]
Changes are available here: #8 

@joygoround - Can you perhaps go through the names in [this file](https://raw.githubusercontent.com/womenincstum/womenincstum.github.io/dev/members.md)?

**Comment by idilsulo** [comment]
Notes from Debarghya:

- [x] Add Prof. Anne Brüggemann-Klein as alumni as well since she created IFF
- [x] Instead of Professors call it something like "responsible faculty" (for Jana)
- [x] Move Debarghya under Finances

**Comment by joygoround** [comment]
@idilsulo I have few comment as well! 
- [x] remove stefanie from Finance to almuni
- [x] add Carmen to alumni
- [x] add student assistance to the structure

**Comment by idilsulo** [comment]
@joygoround - Done ✅ Thanks a lot for the suggestions! Let me know if anything else is required, otherwise I can merge this PR #8
